### ISSUE TITLE
Website still doesnt work. Please Check.

### ISSUE THREAD

**Issue by Ksanbah** [denschub/chrome-mask#12]
This wwebsite isnt accessible on Waterfox. https://k2s.cc/
Please check. Thanks.

**Comment by denschub** [comment]
I just responded to your "review" at https://addons.mozilla.org/en-US/firefox/addon/chrome-mask/reviews/2101722/ - and this bugtracker still isn't the right place to report.

But it seems like it works fine in Firefox either way, so please report that to the Waterfox team. I can't help you.
