### ISSUE TITLE
Mash won't works if profile dir is not on C:

### ISSUE THREAD

**Issue by La-Hire** [denschub/chrome-mask#16]
I find it that if profiles dir is set outside C: disk, the addons can't works
![屏幕截图 2024-08-15 081628](https://github.com/user-attachments/assets/6768895a-c926-4120-b04f-74393d84578f)
the addon didn't show message at the bottom of ui, switch can't work
 if copy the profiles to C: just like C:\Users\test, it will works.

**Comment by denschub** [comment]
My addon isn't doing any manual storage operation. You probably just broke your profile (and *all* extensions and a lot of other stuff in it) by moving a profile. You can't just move profiles around, a lot of things depend on the profile being where it should be.
