### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by toothlessgodzilla** [denschub/chrome-mask#22]
This is what users see when they go to uBlockOrigin/uAssets and click "New issue": https://github.com/uBlockOrigin/uAssets/issues/new/choose

You can show people a similar page here with a button that opens Webcompat.com for users who just want to report a broken site. 

https://github.com/uBlockOrigin/uAssets/tree/master/.github

**Comment by denschub** [comment]
People don't report broken sites, here, though. I am aware of issue templates, and I will add one when there is a need.
