### ISSUE TITLE
Anyway to get it installed on FF 52 esr?

### ISSUE THREAD

**Issue by gamesturbator** [denschub/chrome-mask#24]
Version 52 ESR is literally the last version of Firefox that works with the old _working_ versions of extensions that the new Firefox disables. The Mozilla store won't let me install it, claiming it's corrupt, which it obviously isn't. Thanks.

**Comment by denschub** [comment]
The addon works in Firefox >= 115, and I have no intention of changing that -- especially not for a Firefox version that's 7 years out of date.
