### ISSUE TITLE
Consider spoofing the OS for Linux users

### ISSUE THREAD

**Issue by dannycolin** [denschub/chrome-mask#5]
**Description**

Some websites not only block Firefox but also Chrome/Linux. We should consider if spoofing the OS on Linux is an acceptable solution.

Two solutions:

0. Automatically spoof the OS for the user
1. Offer a second toggle to spoof the OS (it could be automatically turn on by default or not)

**Comment by denschub** [comment]
The goal of this addon is to verify if /any/ UA spoof would be a viable option for us to ship in-product. Sites that block Linux specifically are fairly common, so I think option 0 is a fine solution. Spoofing as Windows will unblock those sites, and we can always narrow it down further when building the in-product intervention.

**Comment by denschub** [comment]
@totallynotbillgates no. The use-case for this addon is to test if a site requires a Chrome spoof so we can ship a spoof inside Firefox (and we can check if a Windows-spoof is required). It's not meant to capture all possible scenarios, and adding more options is a big task that increases complexity a lot, sorry.
