### ISSUE TITLE
Bubble on icon doesnt match active tab in each window

### ISSUE THREAD

**Issue by SuperTux88** [denschub/chrome-mask#9]
After doing some testing with multiple windows for #8, I noticed a little visual bug, where the colored bubble on the icon changes based on the last tab I switched to. This is fine, as long as you have only one window, as the icon then always matches the active tab of this window, but if you have multiple windows, the icon is synchronized between all windows and always shows the same color on all of them.

So if in one window I have a tab where I activated the mask, the bubble turns green in all windows, and if I then switch the tab in another window where the mask isn't enabled, it turns gray again in all the window, even in the window where the tab with the enabled mask is still active.

This is only a little visual bug with the bubble in the icon, the add-on still works as it should in all the windows (as far as I can tell) and shows the correct state of the switch for each window when clicking on the icon.

**Comment by denschub** [comment]
This is one for @dannycolin. We currently [naively update the icon and text for the browser action](https://github.com/denschub/chrome-mask/blob/9672c8c1356ac793f456a030d6bb9e0f42d4cb96/src/background_script.js#L77-L91) globally.

Both `browserAction.setIcon()` and `browserAction.setTitle()` have an [an optional `tabId` paramaters](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon#tabid), so it's possible to change the browser action state only for a given tab. As a bonus side-effect, we could get rid of the `browser.tabs.onActivated` handler - we can just always update the tab-specific icon and title as we already do, and we don't have to do anything on tab switches AFAICT.

Danny, do you feel like working on this, or should I do it? :)

**Comment by SuperTux88** [comment]
Oh, I didn't even notice that the text in the tool-tip is also wrong, I only noticed the flicker of the colored bubble and never stayed still that long over the icon for the tool-tip to appear :D

**Comment by dannycolin** [comment]
@denschub I won't have any free time until the end of next week.

**Comment by denschub** [comment]
Fixed in 4.2.0, which is now live on AMO.
